<template>
    <div>
        <el-button size="small" type="primary" @click="handleDownload" style="margin-bottom:20px">导出</el-button>
        <el-table id="table" ref="multipleTable" :data="list" border fit highlight-current-row>
            <el-table-column label="Days" prop="Days" align="center"></el-table-column>
            <el-table-column label="EndDate" prop="EndDate" align="center"></el-table-column>
            <el-table-column label="IsPoint" prop="IsPoint" align="center"></el-table-column>
            <el-table-column label="OrderNum" prop="OrderNum" align="center"></el-table-column>
            <el-table-column label="PhaseName" prop="PhaseName" align="center"></el-table-column>
            <el-table-column label="PlanID" prop="PlanID" align="center"></el-table-column>
            <el-table-column label="Purpose" prop="Purpose" align="center"></el-table-column>
            <el-table-column label="SZPhaseName" prop="SZPhaseName" align="center"></el-table-column>
            <el-table-column label="SZSubIds" prop="SZSubIds" align="center"></el-table-column>
            <el-table-column label="SZSubName" prop="SZSubName" align="center"></el-table-column>
            <el-table-column label="SZZY" prop="SZZY" align="center"></el-table-column>
            <el-table-column label="SZZYCode" prop="SZZYCode" align="center"></el-table-column>
            <el-table-column label="StartDate" prop="StartDate" align="center"></el-table-column>
            <el-table-column label="Status" prop="Status" align="center"></el-table-column>
            <el-table-column label="SubIds" prop="SubIds" align="center"></el-table-column>
            <el-table-column label="SubName" prop="SubName" align="center"></el-table-column>
            <el-table-column label="TZZY" prop="TZZY" align="center"></el-table-column>
            <el-table-column label="TZZYCode" prop="TZZYCode" align="center"></el-table-column>
            <el-table-column label="TZ_Content" prop="TZ_Content" align="center"></el-table-column>
            <el-table-column label="TZ_Detail" prop="TZ_Detail" align="center"></el-table-column>
            <el-table-column label="TZ_Type" prop="TZ_Type" align="center"></el-table-column>
            <el-table-column label="T_ID" prop="T_ID" align="center"></el-table-column>
        </el-table>
    </div>
</template>
<script lang='ts'>
import { Component, Vue } from 'vue-property-decorator'
import { formatJson } from '@/utils/index.ts'
import { exportJson2Excel, exportTable2Excel } from '@/utils/excel.ts'
@Component({
    components: {}
})
export default class Export extends Vue {
    private list: any = [
        {
            PlanID: '7c0ce99d-51d5-4f59-8756-c5902d8f27a2',
            PhaseName: '装修设计',
            SZPhaseName: '装修设计',
            SubIds: '',
            SubName: '',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'ZXNT',
            IsPoint: '0',
            TZZY: '装修暖通',
            SZZYCode: 'ZXD',
            SZZY: '装修电气',
            Purpose: '与装修水暖建立参照引用关系',
            TZ_Content: '装修暖通平面图',
            TZ_Detail:
                '1.提供设备功率及位置2.提供电动控制阀门参数及位置3.其他需要配电的内容',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-15',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '13c6f6c4-ebe8-49fe-a044-dbffefd11519',
            PhaseName: '装修设计',
            SZPhaseName: '施工图',
            SubIds: '',
            SubName: '',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'YZ',
            IsPoint: '0',
            TZZY: '装修',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose:
                '更新装修专业参照内容，打开整图复核开间、墙体、管井优化等需求等',
            TZ_Content: '水电条件图反馈调整',
            TZ_Detail:
                '1.定位准确的机电孔洞点位2.备注与建筑不同的门垛3.提供校对修改后的厨房、卫生间、洗衣机布置图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-16',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '78d3fa62-048a-4706-a5dd-0601ed6e618b',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'JG',
            SZZY: '结构',
            Purpose: '更新建筑专业参照内容并复核修改内容调整',
            TZ_Content: '校审修改完成版（建筑）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-17',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '08f6f3f7-6a5e-4d8f-a3f9-78426593f44a',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'GPS',
            SZZY: '给排水',
            Purpose: '更新建筑专业参照内容并复核修改内容调整',
            TZ_Content: '校审修改完成版（建筑）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-17',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '81a32c95-1be9-462e-8c48-2e28ff2a346f',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'DQ',
            SZZY: '电气',
            Purpose: '更新建筑专业参照内容并复核修改内容调整',
            TZ_Content: '校审修改完成版（建筑）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-17',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '3fb7de75-ffa8-4f00-abf8-4baa281577f6',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'NT',
            SZZY: '暖通',
            Purpose: '更新建筑专业参照内容并复核修改内容调整',
            TZ_Content: '校审修改完成版（建筑）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-17',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '11603b09-61e4-4bac-8a7a-074d090098cb',
            PhaseName: '施工图',
            SZPhaseName: '装修设计',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'YZ',
            SZZY: '装修硬装',
            Purpose: '更新建筑专业参照内容并复核修改内容调整',
            TZ_Content: '校审修改完成版（建筑）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-17',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '70e663fd-9e11-475a-9dc6-cdbdeeaac9c8',
            PhaseName: '施工图',
            SZPhaseName: '装修设计',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'ZXS',
            SZZY: '装修给排水',
            Purpose: '按需建立引用关系',
            TZ_Content: '校审修改完成版（建筑）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-17',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: 'a7e20755-2306-4a99-b0d8-004763ec8f77',
            PhaseName: '施工图',
            SZPhaseName: '装修设计',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'ZXD',
            SZZY: '装修电气',
            Purpose: '按需建立引用关系',
            TZ_Content: '校审修改完成版（建筑）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-17',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '8d3631e9-2377-4677-a9b1-73fe3a8ac344',
            PhaseName: '施工图',
            SZPhaseName: '装修设计',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'ZXNT',
            SZZY: '装修暖通',
            Purpose: '按需建立引用关系',
            TZ_Content: '校审修改完成版（建筑）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-17',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: 'e7d5be33-94de-41fb-92ad-d3f1b9e2dfd7',
            PhaseName: '施工图',
            SZPhaseName: '装修设计',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'GPS',
            IsPoint: '0',
            TZZY: '给排水',
            SZZYCode: 'ZXS',
            SZZY: '装修给排水',
            Purpose: '装修机电校审，提供完整版给项目审核',
            TZ_Content: '校审修改完成版（给排水）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-18',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: 'ee0cf1a0-4336-4b64-ae0f-0f1495f4db61',
            PhaseName: '施工图',
            SZPhaseName: '装修设计',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'DQ',
            IsPoint: '0',
            TZZY: '电气',
            SZZYCode: 'ZXD',
            SZZY: '装修电气',
            Purpose: '装修机电校审，提供完整版给项目审核',
            TZ_Content: '校审修改完成版（电气）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-19',
            TZ_Type: '非参照提资'
        },
        {
            PlanID: 'f4d5f7bb-6c23-4be1-97a8-39a7c2350279',
            PhaseName: '施工图',
            SZPhaseName: '装修设计',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'NT',
            IsPoint: '0',
            TZZY: '暖通',
            SZZYCode: 'ZXNT',
            SZZY: '装修暖通',
            Purpose: '装修机电校审，提供完整版给项目审核',
            TZ_Content: '校审修改完成版（暖通）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-20',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: 'f3cc7ad9-8f6d-4965-8eee-22fd3e0194b5',
            PhaseName: '施工图',
            SZPhaseName: '装修设计',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'JG',
            IsPoint: '0',
            TZZY: '结构',
            SZZYCode: 'YZ',
            SZZY: '装修硬装',
            Purpose: '根据结构专业审核成果调整图纸',
            TZ_Content: '校审修改完成版（结构）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-21',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: 'f4c5adc9-0166-4d65-a3fd-acc92bff11cd',
            PhaseName: '装修设计',
            SZPhaseName: '装修设计',
            SubIds: '',
            SubName: '',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'YZ',
            IsPoint: '0',
            TZZY: '装修',
            SZZYCode: 'ZXS',
            SZZY: '装修给排水',
            Purpose: '更新装修专业参照内容，校审出图',
            TZ_Content: '校审修改完成版（装修）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-22',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '752cffca-2caa-4136-b6d1-542b90c0a02e',
            PhaseName: '装修设计',
            SZPhaseName: '装修设计',
            SubIds: '',
            SubName: '',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'YZ',
            IsPoint: '0',
            TZZY: '装修',
            SZZYCode: 'ZXD',
            SZZY: '装修电气',
            Purpose: '更新装修专业参照内容，校审出图',
            TZ_Content: '校审修改完成版（装修）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-22',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: 'a8fdcb9b-79a9-48d5-b092-e6949f4b9945',
            PhaseName: '装修设计',
            SZPhaseName: '装修设计',
            SubIds: '',
            SubName: '',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'YZ',
            IsPoint: '0',
            TZZY: '装修',
            SZZYCode: 'ZXNT',
            SZZY: '装修暖通',
            Purpose: '更新装修专业参照内容，校审出图',
            TZ_Content: '校审修改完成版（装修）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-22',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '67a8a4fb-bd20-43e6-b3b3-7f3fc38fd519',
            PhaseName: '装修设计',
            SZPhaseName: '装修设计',
            SubIds: '',
            SubName: '',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'ZXNT',
            IsPoint: '0',
            TZZY: '装修暖通',
            SZZYCode: 'ZXD',
            SZZY: '装修电气',
            Purpose: '更新参照内容，校审出图',
            TZ_Content: '校审修改完成版（装修暖通）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-23',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '7b68eea3-80c1-41a4-8eb3-ce1a0dff9a25',
            PhaseName: '装修设计',
            SZPhaseName: '装修设计',
            SubIds: '',
            SubName: '',
            SZSubIds: '',
            SZSubName: '',
            TZZYCode: 'ZXS',
            IsPoint: '0',
            TZZY: '装修给排水',
            SZZYCode: 'ZXD',
            SZZY: '装修电气',
            Purpose: '更新参照内容，校审出图',
            TZ_Content: '校审修改完成版（装修给排水）',
            TZ_Detail: '校审成果图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-23',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '2f6e80a1-1ecf-4450-be9b-dab8947e473e',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JG',
            IsPoint: '0',
            TZZY: '结构',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose: '最后一次更新各专业参照，并依据各专业意见进行调整',
            TZ_Content: '校审修改完成版（结构）',
            TZ_Detail: '校审成果图，并标记需调整意见',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-24',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '55c5e423-e477-4fcd-adfc-a316ad8c7a4e',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'GPS',
            IsPoint: '0',
            TZZY: '给排水',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose: '最后一次更新各专业参照，并依据各专业意见进行调整',
            TZ_Content: '校审修改完成版（给排水）',
            TZ_Detail: '校审成果图，并标记需调整意见',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-24',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: 'fd3e3433-5e6f-46ea-9c0a-021bd131723e',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'DQ',
            IsPoint: '0',
            TZZY: '电气',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose: '最后一次更新各专业参照，并依据各专业意见进行调整',
            TZ_Content: '校审修改完成版（电气）',
            TZ_Detail: '校审成果图，并标记需调整意见',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-24',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '428b14dd-05d3-4195-a831-1fd93e06aca7',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'NT',
            IsPoint: '0',
            TZZY: '暖通',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose: '最后一次更新各专业参照，并依据各专业意见进行调整',
            TZ_Content: '校审修改完成版（暖通）',
            TZ_Detail: '校审成果图，并标记需调整意见',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-24',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '236fe2a8-76af-4aef-b1e8-e0f86694f1b7',
            PhaseName: '装修设计',
            SZPhaseName: '施工图',
            SubIds: '',
            SubName: '',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'YZ',
            IsPoint: '0',
            TZZY: '装修',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose: '最后一次更新各专业参照，并依据各专业意见进行调整',
            TZ_Content: '校审修改完成版（装修）',
            TZ_Detail: '校审成果图，并标记需调整意见',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-24',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '2679afd7-4b1d-4cc9-b2a4-63d8d7ebeb20',
            PhaseName: '装修设计',
            SZPhaseName: '施工图',
            SubIds: '',
            SubName: '',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'ZXS',
            IsPoint: '0',
            TZZY: '装修给排水',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose: '最后一次更新各专业参照，并依据各专业意见进行调整',
            TZ_Content: '校审修改完成版（装修给排水）',
            TZ_Detail: '校审成果图，并标记需调整意见',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-24',
            TZ_Type: '非参照提资'
        },
        {
            PlanID: '1a46056c-18e1-4b2d-94be-fb43c2fdb345',
            PhaseName: '装修设计',
            SZPhaseName: '施工图',
            SubIds: '',
            SubName: '',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'ZXD',
            IsPoint: '0',
            TZZY: '装修电气',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose: '最后一次更新各专业参照，并依据各专业意见进行调整',
            TZ_Content: '校审修改完成版（装修电气）',
            TZ_Detail: '校审成果图，并标记需调整意见',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-24',
            TZ_Type: '非参照提资'
        },
        {
            PlanID: 'fa0b018d-3127-46b6-a793-9f1dc0cbe575',
            PhaseName: '装修设计',
            SZPhaseName: '施工图',
            SubIds: '',
            SubName: '',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'ZXNT',
            IsPoint: '0',
            TZZY: '装修暖通',
            SZZYCode: 'JZ',
            SZZY: '建筑',
            Purpose: '最后一次更新各专业参照，并依据各专业意见进行调整',
            TZ_Content: '校审修改完成版（装修暖通）',
            TZ_Detail: '校审成果图，并标记需调整意见',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-24',
            TZ_Type: '非参照提资'
        },
        {
            PlanID: '8618281e-a298-4fc7-826b-463ae506edc3',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'JG',
            SZZY: '结构',
            Purpose: '塔楼施工图全专业出图打印/规划施工图出图',
            TZ_Content: '最终出图版（建筑）',
            TZ_Detail: '完整的准确无误的建筑全套图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-25',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '2e0ebcdc-db82-468e-9eda-89568015c89a',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'GPS',
            SZZY: '给排水',
            Purpose: '塔楼施工图全专业出图打印/规划施工图出图',
            TZ_Content: '最终出图版（建筑）',
            TZ_Detail: '完整的准确无误的建筑全套图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-25',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '5000d649-d880-4d00-ac6e-5e11dd40cefe',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'DQ',
            SZZY: '电气',
            Purpose: '塔楼施工图全专业出图打印/规划施工图出图',
            TZ_Content: '最终出图版（建筑）',
            TZ_Detail: '完整的准确无误的建筑全套图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-25',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '903871a2-68e0-491a-a9d0-b6a2831c47c3',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200805000666',
            SZSubName: '1#楼(YJ140n-6)',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'NT',
            SZZY: '暖通',
            Purpose: '塔楼施工图全专业出图打印/规划施工图出图',
            TZ_Content: '最终出图版（建筑）',
            TZ_Detail: '完整的准确无误的建筑全套图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-25',
            TZ_Type: '参照类提资'
        },
        {
            PlanID: '52481a31-1108-4aa9-a6d6-d91dbedab0fc',
            PhaseName: '施工图',
            SZPhaseName: '施工图',
            SubIds: 'WN200805000666',
            SubName: '1#楼(YJ140n-6)',
            SZSubIds: 'WN200728000479',
            SZSubName: '大埔碧桂园后续用地地块',
            TZZYCode: 'JZ',
            IsPoint: '0',
            TZZY: '建筑',
            SZZYCode: 'GH',
            SZZY: '规划',
            Purpose: '塔楼施工图全专业出图打印/规划施工图出图',
            TZ_Content: '最终出图版（建筑）',
            TZ_Detail: '完整的准确无误的建筑全套图',
            Days: '',
            StartDate: '',
            EndDate: '',
            T_ID: '',
            Status: '0',
            OrderNum: 'D-25',
            TZ_Type: '参照类提资'
        }
    ]
    private handleDownload () {
        const tHeader = [
            'Days',
            'EndDate',
            'IsPoint',
            'OrderNum',
            'PhaseName',
            'PlanID',
            'Purpose',
            'SZPhaseName',
            'SZSubIds',
            'SZSubName',
            'SZZY',
            'SZZYCode',
            'StartDate',
            'Status',
            'SubIds',
            'SubName',
            'TZZY',
            'TZZYCode',
            'TZ_Content',
            'TZ_Detail',
            'TZ_Type',
            'T_ID'
        ]
        const filterVal: any = tHeader // 对应标题索引导出的val
        const list = this.list
        const data = formatJson(filterVal, list)
        exportJson2Excel(tHeader, data, 'sheet')
        // exportTable2Excel(tHeader, 'table')
    }
}
</script>
<style lang="stylus" scoped></style>
